CREATE TABLE MOVIE.MV(
MV_ID VARCHAR2(20) NOT NULL
,MV_TTL VARCHAR2(50) NOT NULL
,ENG_TTL VARCHAR2(100) NOT NULL
,SCRN_STT VARCHAR2(18) NOT NULL
,SCRN_TM NUMBER NOT NULL
,OPNG_DT DATE NOT NULL
,GRD VARCHAR2(18) NOT NULL
,PSTR VARCHAR2(1000) NOT NULL
,SMR VARCHAR2(4000) NOT NULL
) TABLESPACE USERS;

CREATE TABLE MOVIE.NTN(
NTN_ID NUMBER NOT NULL
,NTN_NM VARCHAR2(20) NOT NULL
) TABLESPACE USERS;

CREATE TABLE MOVIE.PRDC_PLC(
NTN_ID NUMBER NOT NULL
,MV_ID VARCHAR2(20) NOT NULL
) TABLESPACE USERS;

CREATE TABLE MOVIE.GNR(
GNR_ID NUMBER NOT NULL
,GNR_NM VARCHAR2(10) NOT NULL
) TABLESPACE USERS;

CREATE TABLE MOVIE.MV_GNR(
MV_ID VARCHAR2(20) NOT NULL
,GNR_ID NUMBER NOT NULL
) TABLESPACE USERS;

CREATE TABLE MOVIE.MV_PPL(
MV_PPL_ID VARCHAR2(20) NOT NULL
,PRFL_PCTR VARCHAR2(1000) NOT NULL
,NM VARCHAR2(30) NOT NULL
,RL_NM VARCHAR2(30) NULL
) TABLESPACE USERS;

CREATE TABLE MOVIE.PRDC_PRTCPTN_PPL(
PRDC_PRTCPTN_ID VARCHAR2(20) NOT NULL
,MV_ID VARCHAR2(20) NOT NULL
,MV_PPL_ID VARCHAR2(20) NOT NULL
,MSSN VARCHAR2(18) NOT NULL
,RSPNSBLT_ROL_NM VARCHAR2(30) NULL
) TABLESPACE USERS;

CREATE TABLE MOVIE.CMPN(
CMPN_ID VARCHAR2(20) NOT NULL
,CMPN_NM VARCHAR2(50) NOT NULL
) TABLESPACE USERS;


CREATE TABLE MOVIE.PRDC_PRTCPTN_CMPN(
PRDC_PRTCPTN_CMPN_ID VARCHAR2(20) NOT NULL
,MV_ID VARCHAR2(20) NOT NULL
,CMPN_ID VARCHAR2(20) NOT NULL
,CRCLTN_CD VARCHAR2(18) NOT NULL
) TABLESPACE USERS;

CREATE TABLE MOVIE.PCTR(
PCTR_ID VARCHAR2(20) NOT NULL
,MV_ID VARCHAR2(20) NOT NULL
,TP VARCHAR2(18) NOT NULL
,THMBNL_PCTR VARCHAR2(1000) NOT NULL
,ORGNL_PCTR VARCHAR2(1000) NOT NULL
) TABLESPACE USERS;

CREATE TABLE MOVIE.VD(
VD_ID VARCHAR2(20) NOT NULL
,MV_ID VARCHAR2(20) NOT NULL
,VD_TP VARCHAR2(18) NOT NULL
,VD_TTL VARCHAR2(50) NOT NULL
,THMBNL VARCHAR2(1000) NOT NULL
,VD_PLY_CNT NUMBER NOT NULL
,VD_URL VARCHAR2(1000) NOT NULL
,RGST_DT DATE NOT NULL
) TABLESPACE USERS;

CREATE TABLE MOVIE.FMS_LN(
FMS_LN_ID VARCHAR2(20) NOT NULL
,MV_ID VARCHAR2(20) NOT NULL
,MV_PPL_ID VARCHAR2(20) NOT NULL
,FMS_LN VARCHAR2(500) NOT NULL
,XPLNTN VARCHAR2(500) NULL
,RGST_TM DATE NOT NULL
,RGST_PPL_NM VARCHAR2(30) NOT NULL
,RCMMD_CNT NUMBER NOT NULL
) TABLESPACE USERS;

CREATE TABLE MOVIE.CMMN_CD(
CD_ID VARCHAR2(18) NOT NULL
,CD_NM VARCHAR2(100) NOT NULL
,PRCDNC_CD_ID VARCHAR2(18) NULL
) TABLESPACE USERS;

CREATE TABLE MOVIE.PCTR_RPL(
RPL_ID VARCHAR2(20) NOT NULL
,PCTR_ID VARCHAR2(20) NOT NULL
,RPL_DTL VARCHAR2(1000) NOT NULL
,RPL_WRTR VARCHAR2(30) NOT NULL
,RPL_WRT_TM DATE NOT NULL
,LK_CNT NUMBER NOT NULL
,DSLK_CNT NUMBER NOT NULL
,PRCDNC_RPL_ID VARCHAR2(20) NULL
) TABLESPACE USERS;

CREATE TABLE MOVIE.VD_RPL(
RPL_ID VARCHAR2(20) NOT NULL
,VD_ID VARCHAR2(20) NOT NULL
,RPL_DTL VARCHAR2(1000) NOT NULL
,RPL_WRTR VARCHAR2(30) NOT NULL
,RPL_WRT_TM DATE NOT NULL
,LK_CNT NUMBER NOT NULL
,DSLK_CNT NUMBER NOT NULL
,PRCDNC_RPL_ID VARCHAR2(20) NULL
) TABLESPACE USERS;

CREATE TABLE MOVIE.RTNG(
RTNG_ID VARCHAR2(20) NOT NULL
,MV_ID VARCHAR2(20) NOT NULL
,RTNG NUMBER NOT NULL
,RTNG_DTL VARCHAR2(1000) NOT NULL
,RTNG_WRTR VARCHAR2(30) NOT NULL
,RTNG_WRT_TM DATE NOT NULL
,LK_CNT NUMBER NOT NULL
,DSLK_CNT NUMBER NOT NULL
) TABLESPACE USERS;


CREATE SEQUENCE SEQ_MV_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE CACHE 24 NOORDER;

CREATE SEQUENCE SEQ_NTN_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE CACHE 24 NOORDER;

CREATE SEQUENCE SEQ_GNR_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE CACHE 24 NOORDER;

CREATE SEQUENCE SEQ_MV_PPL_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE CACHE 24 NOORDER;

CREATE SEQUENCE SEQ_PRDC_PRTCPTN_PPL_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE CACHE 24 NOORDER;

CREATE SEQUENCE SEQ_CMPN_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE CACHE 24 NOORDER;

CREATE SEQUENCE SEQ_PRDC_PRTCPTN_CMPN_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE CACHE 24 NOORDER;

CREATE SEQUENCE SEQ_PCTR_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE CACHE 24 NOORDER;

CREATE SEQUENCE SEQ_VD_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE CACHE 24 NOORDER;

CREATE SEQUENCE SEQ_FMS_LN_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE CACHE 24 NOORDER;

CREATE SEQUENCE SEQ_PCTR_RPL_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE CACHE 24 NOORDER;

CREATE SEQUENCE SEQ_VD_RPL_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE CACHE 24 NOORDER;

CREATE SEQUENCE SEQ_RTNG_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE CACHE 24 NOORDER;
