SELECT DEPARTMENT_ID
	 , DEPARTMENT_NAME 
	 , MANAGER_ID 
	 , LOCATION_ID 
  FROM DEPARTMENTS
 WHERE MANAGER_ID = 103
;

SELECT FIRST_NAME 
     , LAST_NAME 
  FROM EMPLOYEES
 WHERE MANAGER_ID = 103
 ORDER BY FIRST_NAME ASC
;

SELECT LAST_NAME 
  FROM EMPLOYEES
 WHERE FIRST_NAME = 'Steven'
 ORDER BY LAST_NAME DESC
;

SELECT CITY 
  FROM LOCATIONS
 WHERE COUNTRY_ID = 'US'
 ORDER BY CITY ASC
;

SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , SALARY 
  FROM EMPLOYEES
 WHERE SALARY BETWEEN 10000 AND 15000
 /*
 WHERE SALARY >= 10000 
   AND SALARY <= 15000
*/
 ORDER BY SALARY DESC
;

SELECT EMPLOYEE_ID 
     , FIRST_NAME 
     , MANAGER_ID 
     , COMMISSION_PCT 
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NULL 
-- AND MANAGER_ID = 100
   AND MANAGER_ID IN 100
 ORDER BY EMPLOYEE_ID ASC
;

SELECT *
  FROM EMPLOYEES
 WHERE (JOB_ID = 'FI_MGR'
    OR JOB_ID = 'ST_MAN')
   AND SALARY <= 10000
 ORDER BY HIRE_DATE ASC
;

SELECT *
  FROM EMPLOYEES
 WHERE (FIRST_NAME = 'Bruce'
    OR LAST_NAME = 'Chen')
   AND JOB_ID = 'FI_ACCOUNT'
;

SELECT *
  FROM EMPLOYEES
 WHERE JOB_ID != 'FI_ACCOUNT'
;

SELECT *
  FROM EMPLOYEES
 WHERE JOB_ID IN ('FI_MGR', 'ST_MAN')
   AND SALARY <= 10000
 ORDER BY HIRE_DATE ASC 
;

SELECT *
  FROM EMPLOYEES
 WHERE JOB_ID != 'FI_MGR'
   AND JOB_ID != 'ST_MAN'
   AND SALARY <= 10000
 ORDER BY HIRE_DATE ASC 
;

SELECT *
  FROM EMPLOYEES
 WHERE JOB_ID NOT IN ('FI_MGR', 'ST_MAN')
   AND SALARY <= 10000
 ORDER BY HIRE_DATE ASC 
;

SELECT *
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE 'S%'
;

SELECT *
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%n'
;

SELECT *
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE 'S%n'
;

SELECT *
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%eve%'
;

SELECT *
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%Ste%'
;

SELECT *
  FROM EMPLOYEES
 WHERE PHONE_NUMBER LIKE '515.%'
 ORDER BY FIRST_NAME DESC 
;

SELECT *
  FROM EMPLOYEES
 WHERE JOB_ID LIKE '%PRES'
 ORDER BY LAST_NAME ASC 
;

SELECT DEPARTMENT_ID 
     , DEPARTMENT_NAME
  FROM DEPARTMENTS
 WHERE DEPARTMENT_NAME LIKE '%I%'
    OR DEPARTMENT_NAME LIKE '%i%'
 ORDER BY LOCATION_ID DESC
;

SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS
 WHERE DEPARTMENT_NAME NOT LIKE '%IT%'
 ORDER BY DEPARTMENT_NAME DESC
;

SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS
 WHERE DEPARTMENT_NAME LIKE '%Co%'
   AND DEPARTMENT_NAME NOT LIKE '%T%'
;

SELECT *
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '___'
;

SELECT *
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '____d'
;

SELECT *
  FROM EMPLOYEES
 WHERE LAST_NAME LIKE '_e%'
;

SELECT JOB_ID
     , COUNT(1)
  FROM EMPLOYEES
 GROUP BY JOB_ID
;

SELECT DEPARTMENT_ID
     , COUNT(1)
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
;

SELECT SUM(SALARY)
  FROM EMPLOYEES
;

SELECT DEPARTMENT_ID
     , SUM(SALARY) AS "연봉의 합"
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
;

SELECT JOB_ID
     , SUM(SALARY) AS "연봉의 합"
  FROM EMPLOYEES
 GROUP BY JOB_ID
;

SELECT DEPARTMENT_ID
     , JOB_ID
     , SUM(SALARY) AS "연봉의 합"
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
     , JOB_ID
;

SELECT DEPARTMENT_ID
     , MAX(SALARY) AS "최고 연봉"
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
;

SELECT JOB_ID
     , MIN(SALARY) AS "최저 연봉"
  FROM EMPLOYEES
 GROUP BY JOB_ID
;

SELECT DEPARTMENT_ID
     , JOB_ID
     , MAX(SALARY) AS "최고 연봉"
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
     , JOB_ID 
;

SELECT MAX(SALARY) AS "최고 연봉"
     , MIN(SALARY) AS "최저 연봉"
     , AVG(SALARY) AS "평균 연봉"
     , SUM(SALARY) AS "연봉의 합"
  FROM EMPLOYEES
;

SELECT DEPARTMENT_ID
	 , COUNT(1) AS "데이터의 수"
	 , MAX(SALARY) AS "최고 연봉"
	 , MIN(SALARY) AS "최저 연봉"
	 , AVG(SALARY) AS "평균 연봉"
	 , SUM(SALARY) AS "연봉의 합"
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
;

SELECT MANAGER_ID
     , COUNT(1)
     , MAX(SALARY)
     , MIN(SALARY)
     , AVG(SALARY)
     , SUM(SALARY)
  FROM EMPLOYEES
 GROUP BY MANAGER_ID
;

SELECT DEPARTMENT_ID
     , MAX(SALARY)
     , MIN(SALARY)
     , AVG(SALARY)
  FROM EMPLOYEES
 WHERE JOB_ID != 'SA_REP'
 GROUP BY DEPARTMENT_ID 
;

SELECT DEPARTMENT_ID 
     , COUNT(1) AS "데이터 수"
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
 HAVING COUNT(1)  >= 3
;

SELECT MANAGER_ID AS "상사의 번호"
     , COUNT(1) AS "부하직원의 수"
  FROM EMPLOYEES
 GROUP BY MANAGER_ID
HAVING COUNT(1) >= 2
;

SELECT JOB_ID
     , AVG(SALARY)
     , MAX(SALARY)
     , MIN(SALARY)
  FROM EMPLOYEES
 GROUP BY JOB_ID
HAVING AVG(SALARY) >= 7000
 ORDER BY AVG(SALARY) ASC
;

SELECT DEPARTMENT_ID
     , COUNT(1)
     , AVG(SALARY)
     , MAX(SALARY)
     , MIN(SALARY)
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
HAVING COUNT(1) >= 3
   AND AVG(SALARY) >= 5000
;

-- 최저 연봉보다 많이 받는 사원들의 모든 정보를 조회
SELECT *
  FROM EMPLOYEES
 WHERE SALARY > (SELECT MIN(SALARY)
                    FROM EMPLOYEES)
;
-- 평균 연봉보다 많이 받는 사원들의 모든 정보를 조회
SELECT *
  FROM EMPLOYEES
 WHERE SALARY > (SELECT AVG(SALARY)
 				   FROM EMPLOYEES)
 ;
-- EMPLOYEES 테이블에서 FIRST_NAME은 Steven LAST_NAME은 King을 MANAGER_ID로 두고있는 모든 데이터를 조회한다.
SELECT *
  FROM EMPLOYEES
 WHERE MANAGER_ID = (SELECT EMPLOYEE_ID
 		  			   FROM EMPLOYEES
 		 			  WHERE FIRST_NAME = 'Steven'
 		   				AND LAST_NAME = 'King')
;
/*
 * EMPLOYEES 테이블에서 EMPLOYEE_ID 가 102번인 사원의 연봉과
 * 동일한 연봉을 받는 모든 사원의 정보를 조회한다.
 * 단, 102번은 조회에서 제외한다.
 */
SELECT *
  FROM EMPLOYEES
 WHERE SALARY = (SELECT SALARY
 				   FROM EMPLOYEES
 				  WHERE EMPLOYEE_ID = 102)
   AND EMPLOYEE_ID != 102
;
/*
 * EMPLOYEES 테이블에서 EMPLOYEE_ID 가 113번인 사원과 동일한 DEPARTMENT_ID를 가지는 모든 사원의 정보를 출력한다.
 * 단, 113번은 조회에서 제외한다.
 */
SELECT *
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID  = (SELECT DEPARTMENT_ID 
 						   FROM EMPLOYEES
 						  WHERE EMPLOYEE_ID	= 113)
   AND EMPLOYEE_ID != 113
;

/* EMPLOYEES 테이블에서
 * (EMPLOYEE_ID 가 115번인) 데이터의 JOB_ID와
 * 같은 JOB_ID를 가진 데이터를 모두 조회한다.
 * 단, 115번은 조회에서 제외한다.
 */

SELECT *
  FROM EMPLOYEES
 WHERE JOB_ID = (SELECT JOB_ID
 				   FROM EMPLOYEES
 				  WHERE EMPLOYEE_ID = 115)
   AND EMPLOYEE_ID != 115
;

/*
 * EMPLOYEES 테이블에서 (FIRST_NAME 이 J로 시작하는 데이터의 JOB_ID)와
 * 같은 JOB_ID를 가진 데이터를 모두 조회한다.
 */
SELECT *
  FROM EMPLOYEES
 WHERE JOB_ID IN (SELECT JOB_ID
 				   FROM EMPLOYEES
 				  WHERE FIRST_NAME LIKE 'J%')
;

/*
 * EMPLOYEES 테이블에서 (EMPLOYEE_ID가 116번, 201번의 데이터의 SALARY)와
 * 같은 SALARY를 가진 데이터를 모두 조회한다.
 * 단, 116번과 201번은 조회에서 제외한다.
 */
SELECT *
  FROM EMPLOYEES
 WHERE SALARY IN (SELECT SALARY
                    FROM EMPLOYEES
                   WHERE EMPLOYEE_ID IN (116, 201))
   AND EMPLOYEE_ID NOT IN (116, 201)
;

/*
 * EMPLOYEE 테이블에서 (EMPLOYEE_ID가 103번, 206, 115번의 데이터의 MANAGER_ID)와
 * 같은 MANAGER_ID를 가진 데이터를 모두 조회한다.
 * 단, 103번, 206번, 115번은 조회에서 제외한다.
 */
SELECT *
  FROM EMPLOYEES
 WHERE MANAGER_ID IN (SELECT MANAGER_ID
 					    FROM EMPLOYEES
 					   WHERE EMPLOYEE_ID IN (103, 206, 115))
   AND EMPLOYEE_ID NOT IN (103, 206, 115)
;

/* (서브 쿼리 문제)
 * IT 부서에서 일하는 사원의 이름과 성을 조회한다.
 */ 

-- IT 부서의 부서번호 조회
SELECT DEPARTMENT_ID
  FROM DEPARTMENTS
 WHERE DEPARTMENT_NAME = 'IT'
;

-- IT 부서위 부서번호로 사원의 이름과 성을 조회
SELECT FIRST_NAME
     , LAST_NAME
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 60
;

-- 위의 2가지를 통합
SELECT FIRST_NAME
     , LAST_NAME
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
                          FROM DEPARTMENTS
                         WHERE DEPARTMENT_NAME = 'IT')
;

/*
 * ((직무명이 'Programmer'인) 사원의 이메일을 조회한다).
 */
SELECT EMAIL
  FROM EMPLOYEES
 WHERE JOB_ID = (SELECT JOB_ID
                   FROM JOBS
                  WHERE JOB_TITLE = 'Programmer')
;

-- JOIN 을 이용해 풀이
SELECT EMAIL
  FROM EMPLOYEES e
     , JOBS j
 WHERE j.JOB_TITLE = 'Programmer'
   AND e.JOB_ID = j.JOB_ID
;

/*
 * Beijing 도시에 있는 부서명을 조회
 */

SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS
 WHERE LOCATION_ID = (SELECT LOCATION_ID
 						FROM LOCATIONS
 					   WHERE CITY = 'Beijing')
;

-- JOIN 을 이용해 풀이
SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS d 
     , LOCATIONS l 
 WHERE l.CITY = 'Beijing'
   AND d.LOCATION_ID = l.LOCATION_ID
;

/*
 * 'Canada' 에 있는 모든 도시명을 조회
 */

SELECT CITY
  FROM LOCATIONS
 WHERE COUNTRY_ID = (SELECT COUNTRY_ID
 					   FROM COUNTRIES
 					  WHERE COUNTRY_NAME = 'Canada')
;

-- JOIN 으로 풀이
SELECT l.CITY
     , c.COUNTRY_NAME
  FROM LOCATIONS l 
     , COUNTRIES c 
 WHERE c.COUNTRY_NAME = 'Canada'
   AND l.COUNTRY_ID = c.COUNTRY_ID
;
 
/*
 * 'United States of America' 국가에 있는 모든 부서명과 부서번호를 조회한다.
 */

SELECT DEPARTMENT_ID
     , DEPARTMENT_NAME
  FROM DEPARTMENTS
 WHERE LOCATION_ID IN (SELECT LOCATION_ID
 						 FROM LOCATIONS
 					    WHERE COUNTRY_ID = (SELECT COUNTRY_ID
 					   						  FROM COUNTRIES
 					   						 WHERE COUNTRY_NAME = 'United States of America'))
;

SELECT d.DEPARTMENT_ID
     , d.DEPARTMENT_NAME
  FROM DEPARTMENTS d 
     , LOCATIONS l
     , COUNTRIES c 
 WHERE c.COUNTRY_NAME = 'United States of America'
   AND d.LOCATION_ID = l.LOCATION_ID 
   AND l.COUNTRY_ID = c.COUNTRY_ID
;
 

/*
 * EMPLOYEES 와 DEPARTMENT를 조인할 결과를 모두 조회
 */

-- ORACLE SQL
SELECT *
  FROM EMPLOYEES e
     , DEPARTMENTS d 
 WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID;
;

-- ANSI SQL (표준 : 어디서든 사용 가능)
SELECT *
  FROM EMPLOYEES EMP
 INNER JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
;

SELECT *
  FROM EMPLOYEES EMP
  LEFT OUTER JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
;

SELECT *
  FROM EMPLOYEES EMP
 RIGHT OUTER JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
;

SELECT *
  FROM EMPLOYEES EMP
 FULL OUTER JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
;

/*
 * IT 부서에서 일하는 모든 사원들의 이름과 부서장 번호를 조회한다.
 */
SELECT EMP.FIRST_NAME
     , DEP.MANAGER_ID
  FROM EMPLOYEES EMP
 INNER JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
 WHERE DEP.DEPARTMENT_NAME = 'IT'
;

/*
 * 'Seattle' 에 존재하는 부서명과 우편번호를 조회한다.
 */
SELECT DEP.DEPARTMENT_NAME
     , LOC.POSTAL_CODE
  FROM DEPARTMENTS DEP
 INNER JOIN LOCATIONS LOC
    ON DEP.LOCATION_ID = LOC.LOCATION_ID
 WHERE LOC.CITY = 'Seattle'
;

/*
 * 145번 사원이 부서장으로 근무하는 부서에 있는 사원들의 이름과 부서명을 조회.
 */

SELECT EMP.FIRST_NAME
     , DEP.DEPARTMENT_NAME 
  FROM EMPLOYEES EMP
 INNER JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID -- 40몇 개가 나온다.
 WHERE DEP.MANAGER_ID = 145
;

SELECT EMP.FIRST_NAME
     , DEP.DEPARTMENT_NAME 
  FROM EMPLOYEES EMP
 INNER JOIN DEPARTMENTS DEP
    ON EMP.EMPLOYEE_ID  = DEP.MANAGER_ID -- 1개가 나온다.
 WHERE DEP.MANAGER_ID = 145
;


/*
 * 직무아이디 가 'ST_CLERK'인 사원의 이름, 성, 직무명, 최저연봉 을 조회
 */

SELECT EMP.FIRST_NAME 
     , EMP.LAST_NAME 
     , JOB.JOB_TITLE
     , JOB.MIN_SALARY
  FROM EMPLOYEES EMP
 INNER JOIN JOBS JOB
    ON EMP.JOB_ID = JOB.JOB_ID
 WHERE EMP.JOB_ID = 'ST_CLERK'
-- WHERE JOB.JOB_ID = 'ST_CLERK' 동일한 의미
;

/*
 * 100번 부서장이 근무하는 부서명, 도시명, 우편번호를 조회
 */
SELECT DEP.DEPARTMENT_NAME
     , LOC.CITY
     , LOC.POSTAL_CODE
  FROM DEPARTMENTS DEP
 INNER JOIN LOCATIONS LOC
    ON DEP.LOCATION_ID = LOC.LOCATION_ID
 WHERE DEP.MANAGER_ID = 100
;

/*
 * 국가 아이디가 'CN' 인 주, 도시, 주소와 국가명을 조회
 */

SELECT LOC.STREET_ADDRESS 주소
     , LOC.CITY 도시
     , LOC.STATE_PROVINCE 주
     , COU.COUNTRY_NAME 국가명
  FROM LOCATIONS LOC
 INNER JOIN COUNTRIES COU
    ON LOC.COUNTRY_ID = COU.COUNTRY_ID
 WHERE COU.COUNTRY_ID = 'CN'
;

/*
 * 도시, 부서명, 이름, 성을 조회.
 */
SELECT LOC.CITY 
     , DEP.DEPARTMENT_NAME
     , EMP.FIRST_NAME
     , EMP.LAST_NAME
  FROM EMPLOYEES EMP
 INNER JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
 INNER JOIN LOCATIONS LOC
    ON DEP.LOCATION_ID = LOC.LOCATION_ID
;

/*
 * 'Canada' 에 근무하는 사원의 이름과 부서명을 조회한다.
 */

SELECT EMP.FIRST_NAME
     , DEP.DEPARTMENT_NAME
  FROM EMPLOYEES EMP
 INNER JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
 INNER JOIN LOCATIONS LOC
    ON DEP.LOCATION_ID = LOC.LOCATION_ID
 INNER JOIN COUNTRIES CNT
    ON LOC.COUNTRY_ID = CNT.COUNTRY_ID
 WHERE CNT.COUNTRY_NAME = 'Canada'
;

/*
 * 'SA_REP' 직무인 사원의 이름, 성, 연봉, 부서명, 직무명을 조회 -- 29건
 */
SELECT EMP.FIRST_NAME
     , EMP.LAST_NAME 
     , EMP.SALARY 
     , DEP.DEPARTMENT_NAME 
     , JOB.JOB_TITLE
  FROM EMPLOYEES EMP
 INNER JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
 INNER JOIN JOBS JOB
    ON EMP.JOB_ID = JOB.JOB_ID
 WHERE JOB.JOB_ID = 'SA_REP'
;

/*
 * 'MK_REP' 직무였던 사원의 이름, 성, 연봉, 부서명, 현재 직무명을 조회 -- 1건
 */
SELECT EMP.FIRST_NAME
     , EMP.LAST_NAME 
     , EMP.SALARY
     , DEP.DEPARTMENT_NAME
     , JOB.JOB_TITLE
  FROM EMPLOYEES EMP
 INNER JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
 INNER JOIN JOBS JOB
    ON EMP.JOB_ID = JOB.JOB_ID
 INNER JOIN JOB_HISTORY JHT
    ON EMP.EMPLOYEE_ID  = JHT.EMPLOYEE_ID
 WHERE JHT.JOB_ID = 'MK_REP'
;

/*
 * 'New Jersey' 주에서 근무중인 사원의 이름, 부서명, 연봉을 조회 -- 0건
 */
SELECT EMP.FIRST_NAME
     , DEP.DEPARTMENT_NAME
     , EMP.SALARY
  FROM EMPLOYEES EMP
 INNER JOIN DEPARTMENTS DEP
   ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
 INNER JOIN LOCATIONS LOC
   ON DEP.LOCATION_ID = LOC.LOCATION_ID
 WHERE LOC.STATE_PROVINCE = 'New Jersey'
;

/*
 * 'C'로 시작하는 도시에서 근무중인 사원의 이름, 부서명, 직무명, 도시명을 조회 -- 0건
 */
SELECT EMP.FIRST_NAME
     , DEP.DEPARTMENT_NAME 
     , JOB.JOB_TITLE
     , LOC.CITY
  FROM EMPLOYEES EMP
 INNER JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
 INNER JOIN JOBS JOB
    ON EMP.JOB_ID = JOB.JOB_ID 
 INNER JOIN LOCATIONS LOC
    ON DEP.LOCATION_ID = LOC.LOCATION_ID
 WHERE LOC.CITY LIKE 'C%'
;

/*
 * 우편번호에 '7' 이 포함된 도시에서 근무중인 사원들의 사원번호, 직무명을 조회 -- 2건
 */
SELECT EMP.EMPLOYEE_ID
     , JOB.JOB_TITLE
  FROM EMPLOYEES EMP
 INNER JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
 INNER JOIN LOCATIONS LOC
    ON DEP.LOCATION_ID = LOC.LOCATION_ID
 INNER JOIN JOBS JOB
    ON EMP.JOB_ID = JOB.JOB_ID
 WHERE LOC.POSTAL_CODE LIKE '%7%'
;

/*
 * 회사 전체 평균연봉보다 많은 연봉을 받는 사원들의 이름과 부서명을 조회 -- 50건
 */
SELECT EMP.FIRST_NAME
     , DEP.DEPARTMENT_NAME
  FROM EMPLOYEES EMP
 INNER JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
 WHERE EMP.SALARY > (SELECT AVG(SALARY)
  				   	   FROM EMPLOYEES) 
;


/*
 * Asia에 근무중인 사원들의 사원번호, 이름, 성, 부서명, 직무명, 도시명을 조회
 */

SELECT EMP.EMPLOYEE_ID 사원번호
     , EMP.FIRST_NAME 이름
     , EMP.LAST_NAME  성
     , DEP.DEPARTMENT_NAME 부서명
     , JOB.JOB_TITLE 직무명
     , LOC.CITY 도시명
  FROM EMPLOYEES EMP
 INNER JOIN JOBS JOB
    ON EMP.JOB_ID = JOB.JOB_ID 
 INNER JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
 INNER JOIN LOCATIONS LOC
    ON DEP.LOCATION_ID = LOC.LOCATION_ID
 INNER JOIN COUNTRIES CNT
    ON LOC.COUNTRY_ID = CNT.COUNTRY_ID
 INNER JOIN REGIONS RGN
    ON CNT.REGION_ID = RGN.REGION_ID
 WHERE RGN.REGION_NAME = 'Asia'
;

/*
 * 사원의( 이름과 부서명 )을 조회, 부서에 포함되어 있거나 포함되지 않은 사원도 모두 조회한다.
 * -> 사원이 기준이 된다. (부서가 없는 사원도 조회해야 하니까)
 */
SELECT EMP.FIRST_NAME 
     , DEP.DEPARTMENT_NAME
  FROM EMPLOYEES EMP                  -- 기준 테이블(조회할 정보)이 먼저 
  LEFT OUTER JOIN DEPARTMENTS DEP     -- 참고 테이블
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
;

/*
 * ( 모든 도시 )에 위치한 부서를 조회
 * ->도시가 기준이된다. (부서가 없는 도시도 조회해야 하니까)
 */
SELECT LOC.CITY
     , DEP.DEPARTMENT_NAME 
  FROM LOCATIONS LOC
  LEFT OUTER JOIN DEPARTMENTS DEP
    ON DEP.LOCATION_ID = LOC.LOCATION_ID
;

/*
 * 모든 도시의 도시별 부서의 개수를 조회  도시명 | 부서개수
 */
SELECT LOC.CITY
     , COUNT(DEP.DEPARTMENT_ID)
--     , COUNT(1) 사용시 [NULL]도 1건으로 갯수를 센다.
  FROM LOCATIONS LOC
  LEFT OUTER JOIN DEPARTMENTS DEP
    ON DEP.LOCATION_ID = LOC.LOCATION_ID
 GROUP BY LOC.CITY
;

/*
 * 국가별 지역의 개수를 조회
 */
SELECT COU.COUNTRY_NAME 
     , COUNT(LOC.LOCATION_ID)
  FROM COUNTRIES COU
  LEFT OUTER JOIN LOCATIONS LOC
    ON COU.COUNTRY_ID = LOC.COUNTRY_ID
 GROUP BY COU.COUNTRY_NAME
;


/*
 * ( 직무별 (사원의 수))를 조회
 */
SELECT JOB.JOB_TITLE 
     , COUNT(EMP.EMPLOYEE_ID)
  FROM JOBS JOB
  LEFT OUTER JOIN EMPLOYEES EMP
    ON JOB.JOB_ID = EMP.JOB_ID
 GROUP BY JOB.JOB_TITLE
;

/*
 * 직무별 사원의 수를 조회. 단, 사원의 수가 5명 이상인 직무만 조회
 */

SELECT JOB.JOB_TITLE 
     , COUNT(EMP.EMPLOYEE_ID)
  FROM JOBS JOB
  LEFT OUTER JOIN EMPLOYEES EMP
    ON JOB.JOB_ID = EMP.JOB_ID
 GROUP BY JOB.JOB_TITLE 
HAVING COUNT(EMP.EMPLOYEE_ID) >= 5
;
  
/*
 * 사원이 단 한 명도 없는 부서명을 조회
 */
SELECT DEP.DEPARTMENT_NAME
     , COUNT(EMP.EMPLOYEE_ID)
  FROM DEPARTMENTS DEP
  LEFT OUTER JOIN EMPLOYEES EMP
    ON DEP.DEPARTMENT_ID = EMP.DEPARTMENT_ID
 GROUP BY DEPARTMENT_NAME 
HAVING COUNT(EMP.EMPLOYEE_ID) = 0
;

SELECT DEP.DEPARTMENT_NAME
     , DEP.DEPARTMENT_ID DEP의DEPID
     , EMP.DEPARTMENT_ID EMP의DEPID
     , EMP.FIRST_NAME 
  FROM DEPARTMENTS DEP
  LEFT OUTER JOIN EMPLOYEES EMP
    ON DEP.DEPARTMENT_ID = EMP.DEPARTMENT_ID
;

SELECT DEP.DEPARTMENT_NAME
  FROM DEPARTMENTS DEP
  LEFT OUTER JOIN EMPLOYEES EMP
    ON DEP.DEPARTMENT_ID = EMP.DEPARTMENT_ID
 WHERE EMP.DEPARTMENT_ID IS NULL
;

SELECT DEP.DEPARTMENT_NAME
  FROM DEPARTMENTS DEP
  LEFT OUTER JOIN EMPLOYEES EMP
    ON DEP.DEPARTMENT_ID = EMP.DEPARTMENT_ID
 WHERE EMP.FIRST_NAME IS NULL
;

SELECT *
  FROM REGIONS REG
  LEFT OUTER JOIN COUNTRIES COU
    ON REG.REGION_ID = COU.REGION_ID 
  LEFT OUTER JOIN LOCATIONS LOC
    ON COU.COUNTRY_ID = LOC.COUNTRY_ID

/*
 * 대륙별 지역의 수를 조회
 */
SELECT REG.REGION_NAME 
     , COUNT(LOC.LOCATION_ID)
  FROM REGIONS REG
  LEFT OUTER JOIN COUNTRIES COU
    ON REG.REGION_ID = COU.REGION_ID 
  LEFT OUTER JOIN LOCATIONS LOC
    ON COU.COUNTRY_ID = LOC.COUNTRY_ID
 GROUP BY REG.REGION_NAME 
;


/*
 * 지역별 사원의 수를 조회
 */

SELECT LOC.CITY 
     , COUNT(EMP.EMPLOYEE_ID)
  FROM LOCATIONS LOC
  LEFT OUTER JOIN DEPARTMENTS DEP
    ON LOC.LOCATION_ID = DEP.LOCATION_ID
  LEFT OUTER JOIN EMPLOYEES EMP
    ON DEP.DEPARTMENT_ID = EMP.DEPARTMENT_ID
 GROUP BY LOC.CITY 
;

/*
 * INNER VIEW (INLINE VIEW) 문제
 * 2005년에 입사한 사원들의 부서명과 이름을 조회
 */
SELECT DEP.DEPARTMENT_NAME 
     , EMP_05.FIRST_NAME
  FROM (SELECT FIRST_NAME    -- 우리가 필요로 하는 COLUMN (*를 쓰지말고 필요로 하는 DATA만을 가져와야한다.)
             , DEPARTMENT_ID -- JOIN 하려는 COLUMN 
  		  FROM EMPLOYEES
  		 WHERE HIRE_DATE BETWEEN TO_DATE('2005-01-01','YYYY-MM-DD') AND TO_DATE('2005-12-31') ) EMP_05 -- INLINE VIEW (107건을 29건으로 줄였다) 도 ALIAS(EMP_05)를 만들어주어야한다.
 INNER JOIN DEPARTMENTS DEP
    ON EMP_05.DEPARTMENT_ID = DEP.DEPARTMENT_ID
;

/*
 * 연봉을 많이 받는 사람들 중 상위 10명의 이름과 부서명을 조회
 */

-- 연봉을 많이 받는 사원 상위 10명 조회
-- 10명을 가져온 후, SALARY를 정렬하므로 이상하게 나온다.    (X)
SELECT *
  FROM EMPLOYEES
 WHERE ROWNUM <= 10
 ORDER BY SALARY DESC
;

-- 정렬을 한 INLINE VIEW에서 10명을 가져온다. = 상위 10명 조회 (O)
SELECT * 
  FROM (SELECT *
 		  FROM EMPLOYEES
 		 ORDER BY SALARY DESC)
 WHERE ROWNUM <= 10
;

-- 부서명까지 조회
SELECT EMP.FIRST_NAME
     , DEP.DEPARTMENT_NAME 
  FROM (SELECT FIRST_NAME      -- 우리가 필요로 하는 DATA
             , DEPARTMENT_ID   -- JOIN 하기 위해 필요한 DATA
 		  FROM EMPLOYEES
 		 ORDER BY SALARY DESC) EMP
 INNER JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
 WHERE ROWNUM <= 10
;

/*
 * 이름으로 내림차순 정렬된 데이터 중 상위 20개의 사원번호, 이름, 부서명을 조회
 */
-- 이름으로 내림차순 정렬 (INLINE VIEW에 넣을 것들)
SELECT *
  FROM EMPLOYEES
 ORDER BY FIRST_NAME DESC
;

-- 상위 20개 가져오기
SELECT *
  FROM (SELECT *
          FROM EMPLOYEES
         ORDER BY FIRST_NAME DESC) EMP
 WHERE ROWNUM <= 20
;

-- 필요한 데이터만 가져오기 (완성)
SELECT EMP.EMPLOYEE_ID
	 , EMP.FIRST_NAME
	 , DEP.DEPARTMENT_NAME
  FROM (SELECT EMPLOYEE_ID -- 필요한 DATA
             , FIRST_NAME  -- 필요한 DATA 
             , DEPARTMENT_ID -- JOIN에 필요한 DATA
          FROM EMPLOYEES
         ORDER BY FIRST_NAME DESC) EMP
 INNER JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
 WHERE ROWNUM <= 20
;

/*
 * 사원수가 가장 많은 부서의 사원명, 부서명을 조회
 */
-- 사원수가 가장 많은 부서 (사원 수 정렬)
SELECT COUNT(1) AS CNT
     , DEPARTMENT_ID
  FROM EMPLOYEES EMP
 GROUP BY DEPARTMENT_ID
 ORDER BY CNT DESC
;
 	
SELECT *
  FROM (SELECT COUNT(1) AS CNT
             , DEPARTMENT_ID
  		  FROM EMPLOYEES EMP
 		 GROUP BY DEPARTMENT_ID)
 ORDER BY CNT DESC
;

-- 그 중 1개 부서를 조회
SELECT DEPARTMENT_ID
  FROM (SELECT COUNT(1) AS CNT
     		, DEPARTMENT_ID
  		 FROM EMPLOYEES EMP
 		GROUP BY DEPARTMENT_ID
 		ORDER BY CNT DESC)
 WHERE ROWNUM = 1
;

 
-- 완성
SELECT DEP.DEPARTMENT_NAME 
     , EMP.FIRST_NAME
  FROM (SELECT DEPARTMENT_ID
		  FROM (SELECT COUNT(1) AS CNT
		     		, DEPARTMENT_ID
		  		 FROM EMPLOYEES EMP
		 		GROUP BY DEPARTMENT_ID
		 		ORDER BY CNT DESC)
		 WHERE ROWNUM = 1) TOP_DEP
 INNER JOIN DEPARTMENTS DEP
    ON TOP_DEP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
 INNER JOIN EMPLOYEES EMP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
;
  
SELECT DEP.DEPARTMENT_NAME 
     , EMP.FIRST_NAME 
  FROM DEPARTMENTS DEP
 INNER JOIN EMPLOYEES EMP
    ON DEP.DEPARTMENT_ID = EMP.DEPARTMENT_ID 
 WHERE DEP.DEPARTMENT_ID = (SELECT DEPARTMENT_ID
							  FROM (SELECT COUNT(1) AS CNT
							             , DEPARTMENT_ID
							          FROM EMPLOYEES
							         GROUP BY DEPARTMENT_ID
							         ORDER BY CNT DESC)
							 WHERE ROWNUM = 1)
;
 
/*
 * 과제 : 
 * 이름으로 오름차순 정렬된 데이터 중 상위 30개와
 * 부서명으로 내림차순 정렬된 데이터 중 상위 5개를 조인해
 * 이름, 부서명, 직무명 을 조회
 */

-- 이름으로 오름차순 정렬된 데이터
SELECT *
  FROM EMPLOYEES
 ORDER BY FIRST_NAME ASC
;

-- 이름으로 오름차순 정렬된 데이터 중 상위 30개와
SELECT *
  FROM (SELECT FIRST_NAME
             , DEPARTMENT_ID
		  FROM EMPLOYEES
		 ORDER BY FIRST_NAME ASC)
 WHERE ROWNUM <= 30
;

-- 부서명으로 내림차순 정렬된 데이터
SELECT *
  FROM DEPARTMENTS
 ORDER BY DEPARTMENT_NAME DESC
;

-- 부서명으로 내림차순 정렬된 데이터 중 상위 5개
SELECT *
  FROM (SELECT DEPARTMENT_NAME 
             , DEPARTMENT_ID
		  FROM DEPARTMENTS
		 ORDER BY DEPARTMENT_NAME DESC)
 WHERE ROWNUM <= 5
;

-- 이름으로 오름차순 정렬된 데이터 중 상위 30개와 부서명으로 내림차순 정렬된 데이터 중 상위 5개를 조인해 이름, 부서명, 직무명 을 조회
SELECT TOP_EMP.FIRST_NAME
     , TOP_DEP.DEPARTMENT_NAME
     , JOB.JOB_TITLE
  FROM (SELECT FIRST_NAME               -- 필요한 DATA
             , DEPARTMENT_ID            -- JOIN DATA 
             , JOB_ID                   -- JOIN DATA
		  FROM (SELECT FIRST_NAME       
             		 , DEPARTMENT_ID
             		 , JOB_ID
				  FROM EMPLOYEES
				 ORDER BY FIRST_NAME ASC)
		 WHERE ROWNUM <= 30) TOP_EMP   -- 이름으로 오름차순 정렬된 데이터 중 상위 30개
 INNER JOIN (SELECT DEPARTMENT_NAME              -- 필요한 DATA
            	  , DEPARTMENT_ID                -- JOIN DATA
			   FROM (SELECT DEPARTMENT_NAME 
            			  , DEPARTMENT_ID
			 		   FROM DEPARTMENTS
					  ORDER BY DEPARTMENT_NAME DESC)
			  WHERE ROWNUM <= 5) TOP_DEP   -- 부서명으로 내림차순 정렬된 데이터 중 상위 5개
	ON TOP_EMP.DEPARTMENT_ID = TOP_DEP.DEPARTMENT_ID
 INNER JOIN JOBS JOB
    ON JOB.JOB_ID = TOP_EMP.JOB_ID
;






















